# Generated by Django 2.0.1 on 2018-01-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniature_potato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
