# Generated by Django 2.0.1 on 2018-01-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniature_potato', '0003_auto_20180115_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
